// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickTypeCorresp;
//
//    var indicesCorrespondance = IndicesCorrespondance.FromJson(jsonString);

namespace QuickTypeCorresp
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class IndicesCorrespondance
    {
        [JsonProperty("id", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        [JsonProperty("nom", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public string Nom { get; set; }
    }

    public partial class IndicesCorrespondance
    {
        public static IndicesCorrespondance[] FromJson(string json)
        {
            return JsonConvert.DeserializeObject<IndicesCorrespondance[]>(json, QuickTypeCorresp.Converter.Settings);
        }
    }

    public static class Serialize
    {
        public static string ToJson(this IndicesCorrespondance[] self)
        {
            return JsonConvert.SerializeObject(self, QuickTypeCorresp.Converter.Settings);
        }
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
