// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickTypeIND;
//
//    var indicesTxt = IndicesTxt.FromJson(jsonString);

namespace QuickTypeIND
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class IndicesTxt
    {
        [JsonProperty("id", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        [JsonProperty("value", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public string Value { get; set; }
    }

    public partial class IndicesTxt
    {
        public static List<IndicesTxt> FromJson(string json)
        {
            return JsonConvert.DeserializeObject<List<IndicesTxt>>(json, QuickTypeIND.Converter.Settings);
        }
    }

    public static class Serialize
    {
        public static string ToJson(this List<IndicesTxt> self)
        {
            return JsonConvert.SerializeObject(self, QuickTypeIND.Converter.Settings);
        }
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
