// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickTypePOI;
//
//    var pointOfInterest = PointOfInterest.FromJson(jsonString);

namespace QuickTypePOI
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class PointOfInterest
    {
        [JsonProperty("id", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        [JsonProperty("nameId", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public long? NameId { get; set; }

        [JsonProperty("categoryId", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public long? CategoryId { get; set; }
    }

    public partial class PointOfInterest
    {
        public static List<PointOfInterest> FromJson(string json)
        {
            return JsonConvert.DeserializeObject<List<PointOfInterest>>(json, QuickTypePOI.Converter.Settings);
        }
    }

    public static class Serialize
    {
        public static string ToJson(this List<PointOfInterest> self)
        {
            return JsonConvert.SerializeObject(self, QuickTypePOI.Converter.Settings);
        }
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
